name: Проверка 1.1.3 Запуск прошивки

on:
  workflow_call:
    inputs:
      project:
        description: Папка проекта в репозитории обучающегося
        required: false
        type: string
        default: "112-blink"

jobs:
  check:
    name: Запуск прошивки
    runs-on: ubuntu-latest
    steps:
      - name: Репозиторий обучающегося
        uses: actions/checkout@v4
        with:
          path: student

      - name: Проверки курса
        uses: actions/checkout@v4
        with:
          repository: ant-lab-ru/es-test
          path: es-test

      - name: Инструменты сборки
        uses: ant-lab-ru/es-test/.github/actions/pico-toolchain@master

      - name: Проверка
        run: es-test/checks/check-1-1-3.sh student "${{ inputs.project }}"
